### PR TITLE
added katib

### PR DESCRIPTION
**Pull request by Edwardsleo**

### CODE REVIEW

**Comment by prem0912** [comment]
change folder name from tf-katib to tf-katib deploy service

**Comment by prem0912** [comment]
Create new folder as "docker-images" in covid/onprem/pipelines/chest-xray/ location and move "katib-train" folder from "chest-xray-katib" to docker-images folder

**Comment by Edwardsleo** [comment]
> change folder name from tf-katib to tf-katib deploy service

folder created.

**Comment by Edwardsleo** [comment]
> Create new folder as "docker-images" in covid/onprem/pipelines/chest-xray/ location and move "katib-train" folder from "chest-xray-katib" to docker-images folder

moved katib-train folder to the chest xray location

**Pull request merged**
