### PR TITLE
added network visulization

### PR DESCRIPTION
**Pull request by Edwardsleo**

### CODE REVIEW

**Comment by prem0912** [comment]
@Edwardsleo  Merge Network_Classification_GPU.ipynb and Network_Classification_CPU.ipynb into a single file.
Example from https://github.com/Edwardsleo/cisco-kubeflow-starter-pack/tree/dev/apps/networking/ble-localization/onprem/notebook

**Comment by prem0912** [comment]
@Edwardsleo Why covid filename present in network-traffic/pipelines/pictures folder..?
Did you copy files from covid pictures or just named filesnames with covid...?
Please change name or SS accordingly

**Comment by Edwardsleo** [comment]
> @Edwardsleo Merge Network_Classification_GPU.ipynb and Network_Classification_CPU.ipynb into a single file.
> Example from https://github.com/Edwardsleo/cisco-kubeflow-starter-pack/tree/dev/apps/networking/ble-localization/onprem/notebook

merged CPU & GPU notebook

**Comment by Edwardsleo** [comment]
> @Edwardsleo Why covid filename present in network-traffic/pipelines/pictures folder..?
> Did you copy files from covid pictures or just named filesnames with covid...?
> Please change name or SS accordingly

addressed this issue..

**Pull request merged**
